name: My First Action

on:
  push:
    branches: [master]

jobs:
  react_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch origin/master
      run: |
        git fetch origin master

    - name: Get commit details
      id: get_commit_details
      run: |
        # Get the number of new commits compared to origin/master
        COMMIT_COUNT=$(git rev-list --count HEAD ^origin/master)
        
        # If there are new commits, gather details
        if [ "$COMMIT_COUNT" -gt 0 ]; then
          git log --oneline --pretty=format:"%h %s - %an" -n $COMMIT_COUNT > commit_details.txt
        else
          echo "No new commits" > commit_details.txt
        fi
        
        # Set environment variables for commit count and details
        echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
        echo "COMMIT_DETAILS=$(cat commit_details.txt)" >> $GITHUB_ENV

    - name: Send message to Discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
          ${{ github.repository }} has been successfully pushed to master.
          ${{ env.COMMIT_COUNT }} new commit(s):
          ${{ env.COMMIT_DETAILS }}
